### ISSUE TITLE
Remove multiple use of settings context manager in tests

### ISSUE THREAD

**Issue by marcofucci** [UKTradeInvestment/export-wins-data#2]
There seems to be way too many calls to the settings context manager.
It would make sense to explore other solutions like `override_settings` on the TestCase class or a settings for the test to make the code easier to read.

**Comment by danielquinn** [comment]
For the record, this was the fix:

```python
from django.test import override_settings, TestCase

class MyTestCase(TestCase):

    @override_settings(UI_SECRET=AliceClient.SECRET)
    def test_whatever(self):
        ...
```
