### ISSUE TITLE
Avoid hardcoding schema urls

### ISSUE THREAD

**Issue by marcofucci** [UKTradeInvestment/export-wins-data#4]
In your tests you build the schema url by hand in this way:

`self.wins_schema = "{}schema/".format(reverse("drf:win-list"))`

it would be cleaner to use the built-in reverse functionality instead:

`self.wins_schema = reverse("drf:win-schema")`

**Comment by danielquinn** [comment]
DRF "actions" are new to me, so I didn't know that this was a thing.  Thanks.
